#!/bin/bash

set -e
set -u

outfile="${1}"
version="${2}"

set +e
sha="$(git describe 2> /dev/null)"
set -e


cat > "${outfile}" << EOF
#ifndef _PUD_VERSION_H_
#define _PUD_VERSION_H_

#define PLUGIN_VER "${version}"
EOF

if [[ -n "${sha:-}" ]]; then
  cat >> "${outfile}" << EOF
#define GIT_SHA    "${sha}"
EOF
fi

cat >> "${outfile}" << EOF

#endif /* _PUD_VERSION_H_ */
EOF
