.\"                                      Hey, EMACS: -*- nroff -*-
.TH olsrd-gui 1 "2012"
.SH NAME
olsrd-gui \- control and view status of olsrd routing daemon
.SH SYNOPSIS
.B olsrd-gui
[
.B "host-or-IP"
]
.SH DESCRIPTION
This manual page documents briefly the
.B olsrd-gui
command.  It connects to a running olsrd over an IPC connection
configured in 
.B /etc/olsrd/olsrd.conf
.
.PP
.SH SEE ALSO
.BR olsrd (8),
.BR olsrd-conf (5).
.br
.SH AUTHOR
olsrd-gui was written by Andreas Tonnesen <andreto@ifi.uio.no>.
